version = 0.1
[default.deploy.parameters]
stack_name = "ai-discord-chatbot-app"
resolve_s3 = true
s3_prefix = "ai-discord-chatbot-app"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
disable_rollback = false
image_repositories = []
